### ISSUE TITLE
problem if filename contain unicode characters

### ISSUE THREAD

**Issue by redbrain17** [shbhrsaha/syndicate#5]
I'am using your code 5 years in production on my raspberry pi to generate a website. So thanks a lot. 
Now I found a little issue for files that contains unicode chars. For example german umlaute like "äüö"

These files where just skipped. I'll provide you a fix

**Comment by shbhrsaha** [comment]
Wow, I had no idea anyone used this. Just merged. Thanks for contributing the fix!
